spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

logging:
  level:
    org: ERROR

episodes:
  queue:
    name: podcast.episode.published
    durable: true
    exclusive: false
    auto-delete: false
  client:
    duration: 10000