version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./admin/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - clickhouse-setup_default

  admin:
    build: ./admin
    tty: true
    command: bash -c "./bin/dev"
    networks:
      - clickhouse-setup_default
    environment:
      - OTEL_EXPORTER=otlp
      - OTEL_SERVICE_NAME=kelex-web-admin
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES='host.name=kelex-web-admin,os.type=linux,service.name=kelex-web-admin'
    volumes:
      - ./admin:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    networks:
      - clickhouse-setup_default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  locust:
    image: locustio/locust
    networks:
      - clickhouse-setup_default
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    # command: -f /mnt/locust/locustfile.py --host=http://web:3000
    command: -f /mnt/locust/locustfile.py --host=http://localhost:8080

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: es
    networks:
      - clickhouse-setup_default
    volumes:
      - ./.esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  bff:
    build:
      context: ./web-player-bff
      dockerfile: Dockerfile
    networks:
      - clickhouse-setup_default
    environment:
      - OTEL_EXPORTER=otlp
      - OTEL_SERVICE_NAME=kelex-bff
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES='host.name=kelex-bff,os.type=linux,service.name=kelex-bff'
    ports:
      - "8087:8080"
    depends_on:
      - es

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - "xpack.security.enabled=false"
    ports:
      - 5601:5601
    depends_on:
      - es

  consumers:
    build:
      context: ./consumers
      dockerfile: Dockerfile
    networks:
      - clickhouse-setup_default
    environment:
      - OTEL_EXPORTER=otlp
      - OTEL_SERVICE_NAME=kelex-consumers
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz-otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES='host.name=kelex-consumers,os.type=linux,service.name=kelex-consumers'
    ports:
      - "8080:8080"
    depends_on:
      - es
      - rabbitmq

networks:
  clickhouse-setup_default:
    external: true