require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/podcasts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Podcast. As you add validations to Podcast, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Podcast.create! valid_attributes
      get podcasts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      podcast = Podcast.create! valid_attributes
      get podcast_url(podcast)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_podcast_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      podcast = Podcast.create! valid_attributes
      get edit_podcast_url(podcast)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Podcast" do
        expect {
          post podcasts_url, params: { podcast: valid_attributes }
        }.to change(Podcast, :count).by(1)
      end

      it "redirects to the created podcast" do
        post podcasts_url, params: { podcast: valid_attributes }
        expect(response).to redirect_to(podcast_url(Podcast.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Podcast" do
        expect {
          post podcasts_url, params: { podcast: invalid_attributes }
        }.to change(Podcast, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post podcasts_url, params: { podcast: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested podcast" do
        podcast = Podcast.create! valid_attributes
        patch podcast_url(podcast), params: { podcast: new_attributes }
        podcast.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the podcast" do
        podcast = Podcast.create! valid_attributes
        patch podcast_url(podcast), params: { podcast: new_attributes }
        podcast.reload
        expect(response).to redirect_to(podcast_url(podcast))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        podcast = Podcast.create! valid_attributes
        patch podcast_url(podcast), params: { podcast: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested podcast" do
      podcast = Podcast.create! valid_attributes
      expect {
        delete podcast_url(podcast)
      }.to change(Podcast, :count).by(-1)
    end

    it "redirects to the podcasts list" do
      podcast = Podcast.create! valid_attributes
      delete podcast_url(podcast)
      expect(response).to redirect_to(podcasts_url)
    end
  end
end
